### ISSUE TITLE
not working trackers in best.txt

### ISSUE THREAD

**Issue by mrx23dot** [XIU2/TrackersListCollection#29]
Please pre-filter trackers, these are not working

http://0205.uptm.ch:6969/announce	working	25m 53s	0	0	0		  -> 0 peers, not big tracker, not best
http://ipv6-publictracker.zooki.xyz:6969/announce	hostname not found	48s	0	0	0	
http://share.camoe.cn:8080/announce	working	56m 59s	0	0	0	  -> 0 peers, not big tracker, not best
http://torrent.nwps.ws:80/announce	HTTP Error 404	27m 1s	0	0	0	
http://tracker.bt4g.com:2095/announce	working	17m 4s	0	0	0		  -> 0 peers, not big tracker, not best
http://tracker.ipv6tracker.ru:80/announce	hostname not found	57s	0	0	0	
udp://exodus.desync.c	No such host is known.	17m 44s	0	0	0	
udp://tracker.trackerfix.com:81/announce	Connection timed out.	19m 9s	0	0	0

**Comment by XIU2** [comment]
The original intention of this project is to consolidate the list of popular trackers, **and does not strictly maintain every Tracker server.**

Because of the lack of an automated monitoring Tracker tool that meets my requirements, I simply filter some invalid Tracker servers.
****
I will add some of the Tracker you provided to the blacklist.

### Add to blacklist:
* `http://torrent.nwps.ws:80/announce` (The domain name resolves to 127.0.0.1.)

> **Note: Effective tomorrow.**
****
### The description is incorrect:
* `http://ipv6-publictracker.zooki.xyz:6969/announce` (IP: 2a05:9403::167)
* `http://tracker.ipv6tracker.ru:80/announce` (IP: 2a01:4f8:200:2241::ac15:173)
* `udp://exodus.desync.c` (should be: **udp://exodus.desync.com:6969/announce**, IP: 208.83.20.20)
****
### Ignore the following:

Because I cannot effectively monitor each Tracker server automatically, I will not filter this type of Tracker.

* `http://0205.uptm.ch:6969/announce`
* `http://share.camoe.cn:8080/announce`
* `http://tracker.bt4g.com:2095/announce`
* `udp://tracker.trackerfix.com:81/announce`
****
## Currently, Tracker server filter conditions:
* The domain name is not correctly resolved (hostname not found).
`Later, I will add 127.0.0.1 to the filter list.`
* HTTP/HTTPS Tracker server is not responding.
`TCP port test.`
* HTTPS protocol, but no domain name
`for example: https://1.2.3.4:443 , Such SSL certificates are not trusted.`
